using MarkZither.KimaiDotNet.Models;

using Microsoft.Rest;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace MarkZither.KimaiDotNet.ExcelAddin.Services
{
    public class MockKimaiServices : IKimaiServices
    {
        private string Username { get; }
        private string Password { get; set; }
        private string ApiUrl { get; set; }
        private HttpClient Client { get; set; }

        readonly Random rnd = new Random(DateTime.Now.Millisecond); //DevSkim: ignore DS148264
        public MockKimaiServices()
        {
            Username = Globals.ThisAddIn.ApiUsername;
            Password = Globals.ThisAddIn.ApiPassword;
            ApiUrl = Globals.ThisAddIn.ApiUrl;
            Client = new HttpClient
            {
                BaseAddress = new Uri(ApiUrl),
            };
            Client.DefaultRequestHeaders.Add("X-AUTH-USER", Username);
            Client.DefaultRequestHeaders.Add("X-AUTH-TOKEN", Password);
        }
        public MockKimaiServices(string username, string password, string apiUrl)
        {
            Username = username;
            Password = password;
            ApiUrl = apiUrl;
            Client = new HttpClient
            {
                BaseAddress = new Uri(ApiUrl),
            };
            Client.DefaultRequestHeaders.Add("X-AUTH-USER", Username);
            Client.DefaultRequestHeaders.Add("X-AUTH-TOKEN", Password);
        }
#pragma warning disable MA0051 // Method is too long
        public async Task<IList<ProjectCollection>> GetProjects()
#pragma warning restore MA0051 // Method is too long
        {
            var projects = new List<ProjectCollection>
            {
                new ProjectCollection() { Id = 428, ParentTitle = "CustomerDupeProj", Name = "CustomerDupeProj - Project 1", Customer = 190 },
                new ProjectCollection() { Id = 769, ParentTitle = "CustomerDupeProj", Name = "CustomerDupeProj - Project 1", Customer = 190 },
                new ProjectCollection() { Id = 770, ParentTitle = "Customer7", Name = "Customer7 - Project 3", Customer = 498 },
                new ProjectCollection() { Id = 429, ParentTitle = "Customer8", Name = "Customer8 - Project 4", Customer = 198 },
                new ProjectCollection() { Id = 732, ParentTitle = "Customer9", Name = "Customer9 - Project 5", Customer = 468 },
                new ProjectCollection() { Id = 430, ParentTitle = "Customer10", Name = "Customer10 - Project 6", Customer = 194 },
                new ProjectCollection() { Id = 431, ParentTitle = "Customer11", Name = "Customer11 - Project 7", Customer = 199 },
                new ProjectCollection() { Id = 740, ParentTitle = "Customer12", Name = "Customer12 - Project 8", Customer = 471 },
                new ProjectCollection() { Id = 394, ParentTitle = "Customer91", Name = "Customer91 - Project 9", Customer = 1 },
                new ProjectCollection() { Id = 432, ParentTitle = "Customer13", Name = "Customer13 - Project 10", Customer = 395 },
                new ProjectCollection() { Id = 423, ParentTitle = "Customer13", Name = "Customer13 - Project 11", Customer = 395 },
                new ProjectCollection() { Id = 421, ParentTitle = "Customer14", Name = "Customer14 - Project 12", Customer = 393 },
                new ProjectCollection() { Id = 433, ParentTitle = "Customer14", Name = "Customer14 - Project 13", Customer = 393 },
                new ProjectCollection() { Id = 405, ParentTitle = "Customer15", Name = "Customer15 - Project 14", Customer = 195 },
                new ProjectCollection() { Id = 434, ParentTitle = "Customer15", Name = "Customer15 - Project 15", Customer = 195 },
                new ProjectCollection() { Id = 435, ParentTitle = "Customer16", Name = "Customer16 - Project 16", Customer = 200 },
                new ProjectCollection() { Id = 436, ParentTitle = "Customer17", Name = "Customer17 - Project 17", Customer = 388 },
                new ProjectCollection() { Id = 416, ParentTitle = "Customer17", Name = "Customer17 - Project 18", Customer = 388 },
                new ProjectCollection() { Id = 438, ParentTitle = "Customer18", Name = "Customer18 - Project 19", Customer = 378 },
                new ProjectCollection() { Id = 439, ParentTitle = "Customer19", Name = "Customer19 - Project 20", Customer = 202 },
                new ProjectCollection() { Id = 441, ParentTitle = "Customer20", Name = "Customer20 - Project 21", Customer = 203 },
                new ProjectCollection() { Id = 411, ParentTitle = "Customer21", Name = "Customer21 - Project 22", Customer = 204 },
                new ProjectCollection() { Id = 443, ParentTitle = "Customer21", Name = "Customer21 - Project 23", Customer = 204 },
                new ProjectCollection() { Id = 640, ParentTitle = "Customer22", Name = "Customer22 - Project 24", Customer = 406 },
                new ProjectCollection() { Id = 407, ParentTitle = "Customer23", Name = "Customer23 - Project 25", Customer = 379 },
                new ProjectCollection() { Id = 444, ParentTitle = "Customer23", Name = "Customer23 - Project 26", Customer = 379 },
                new ProjectCollection() { Id = 446, ParentTitle = "Customer24", Name = "Customer24 - Project 27", Customer = 205 },
                new ProjectCollection() { Id = 448, ParentTitle = "Customer25", Name = "Customer25 - Project 28", Customer = 196 },
                new ProjectCollection() { Id = 450, ParentTitle = "Customer26", Name = "Customer26 - Project 29", Customer = 206 },
                new ProjectCollection() { Id = 649, ParentTitle = "Customer27", Name = "Customer27 - Project 30", Customer = 412 },
                new ProjectCollection() { Id = 650, ParentTitle = "Customer27", Name = "Customer27 - Project 31", Customer = 412 },
                new ProjectCollection() { Id = 419, ParentTitle = "Customer28", Name = "Customer28 - Project 32", Customer = 391 },
                new ProjectCollection() { Id = 451, ParentTitle = "Customer28", Name = "Customer28 - Project 33", Customer = 391 },
                new ProjectCollection() { Id = 453, ParentTitle = "Customer29", Name = "Customer29 - Project 34", Customer = 207 },
                new ProjectCollection() { Id = 782, ParentTitle = "Customer30", Name = "Customer30 - Project 35", Customer = 507 },
                new ProjectCollection() { Id = 454, ParentTitle = "Customer31", Name = "Customer31 - Project 36", Customer = 208 },
                new ProjectCollection() { Id = 455, ParentTitle = "Customer32", Name = "Customer32 - Project 37", Customer = 209 },
                new ProjectCollection() { Id = 457, ParentTitle = "Customer33", Name = "Customer33 - Project 38", Customer = 197 },
                new ProjectCollection() { Id = 767, ParentTitle = "Customer34", Name = "Customer34 - Project 39", Customer = 497 },
                new ProjectCollection() { Id = 717, ParentTitle = "Customer35", Name = "Customer35 - Project 40", Customer = 452 },
                new ProjectCollection() { Id = 422, ParentTitle = "Customer36", Name = "Customer36 - Project 41", Customer = 394 },
                new ProjectCollection() { Id = 458, ParentTitle = "Customer36", Name = "Customer36 - Project 42", Customer = 394 },
                new ProjectCollection() { Id = 460, ParentTitle = "Customer37", Name = "Customer37 - Project 43", Customer = 213 },
                new ProjectCollection() { Id = 461, ParentTitle = "Customer38", Name = "Customer38 - Project 44", Customer = 214 },
                new ProjectCollection() { Id = 463, ParentTitle = "Customer39", Name = "Customer39 - Project 45", Customer = 215 },
                new ProjectCollection() { Id = 696, ParentTitle = "Customer40", Name = "Customer40 - Project 46", Customer = 431 },
                new ProjectCollection() { Id = 634, ParentTitle = "Customer41", Name = "Customer41 - Project 47", Customer = 216 },
                new ProjectCollection() { Id = 464, ParentTitle = "Customer41", Name = "Customer41 - Project 48", Customer = 216 },
                new ProjectCollection() { Id = 466, ParentTitle = "Customer42", Name = "Customer42 - Project 49", Customer = 217 },
                new ProjectCollection() { Id = 383, ParentTitle = "Customer43", Name = "Customer43 - Project 50", Customer = 211 },
                new ProjectCollection() { Id = 742, ParentTitle = "Customer43", Name = "Customer43 - Project 51", Customer = 211 },
                new ProjectCollection() { Id = 467, ParentTitle = "Customer43", Name = "Customer43 - Project 52", Customer = 211 },
                new ProjectCollection() { Id = 469, ParentTitle = "Customer44", Name = "Customer44 - Project 53", Customer = 210 },
                new ProjectCollection() { Id = 471, ParentTitle = "Customer45", Name = "Customer45 - Project 54", Customer = 212 },
                new ProjectCollection() { Id = 737, ParentTitle = "Customer46", Name = "Customer46 - Project 55", Customer = 416 },
                new ProjectCollection() { Id = 748, ParentTitle = "Customer46", Name = "Customer46 - Project 56", Customer = 416 },
                new ProjectCollection() { Id = 757, ParentTitle = "Customer47", Name = "Customer47 - Project 57", Customer = 488 },
                new ProjectCollection() { Id = 473, ParentTitle = "Customer48", Name = "Customer48 - Project 58", Customer = 218 },
                new ProjectCollection() { Id = 475, ParentTitle = "Customer49", Name = "Customer49 - Project 59", Customer = 219 },
                new ProjectCollection() { Id = 476, ParentTitle = "Customer50", Name = "Customer50 - Project 60", Customer = 220 },
                new ProjectCollection() { Id = 690, ParentTitle = "Customer51", Name = "Customer51 - Project 61", Customer = 425 },
                new ProjectCollection() { Id = 679, ParentTitle = "Customer52", Name = "Customer52 - Project 62", Customer = 417 },
                new ProjectCollection() { Id = 743, ParentTitle = "Customer53", Name = "Customer53 - Project 63", Customer = 474 },
                new ProjectCollection() { Id = 478, ParentTitle = "Customer54", Name = "Customer54 - Project 64", Customer = 221 },
                new ProjectCollection() { Id = 480, ParentTitle = "Customer55", Name = "Customer55 - Project 65", Customer = 222 },
                new ProjectCollection() { Id = 481, ParentTitle = "Customer56", Name = "Customer56 - Project 66", Customer = 223 },
                new ProjectCollection() { Id = 483, ParentTitle = "Customer57", Name = "Customer57 - Project 67", Customer = 224 },
                new ProjectCollection() { Id = 754, ParentTitle = "Customer58", Name = "Customer58 - Project 68", Customer = 486 },
                new ProjectCollection() { Id = 487, ParentTitle = "Customer66", Name = "Customer66 - Project 69", Customer = 229 },
                new ProjectCollection() { Id = 681, ParentTitle = "Customer59", Name = "Customer59 - Project 70", Customer = 418 },
                new ProjectCollection() { Id = 695, ParentTitle = "Customer60", Name = "Customer60 - Project 71", Customer = 430 },
                new ProjectCollection() { Id = 489, ParentTitle = "Customer67", Name = "Customer67 - Project 72", Customer = 230 },
                new ProjectCollection() { Id = 726, ParentTitle = "Customer61", Name = "Customer61 - Project 73", Customer = 462 },
                new ProjectCollection() { Id = 683, ParentTitle = "Customer62", Name = "Customer62 - Project 74", Customer = 419 },
                new ProjectCollection() { Id = 485, ParentTitle = "Customer63", Name = "Customer63 - Project 75", Customer = 228 },
                new ProjectCollection() { Id = 491, ParentTitle = "Customer68", Name = "Customer68 - Project 76", Customer = 231 },
                new ProjectCollection() { Id = 641, ParentTitle = "Customer64", Name = "Customer64 - Project 77", Customer = 407 },
                new ProjectCollection() { Id = 720, ParentTitle = "Customer65", Name = "Customer65 - Project 78", Customer = 455 },
                new ProjectCollection() { Id = 693, ParentTitle = "Customer69", Name = "Customer69 - Project 79", Customer = 421 },
                new ProjectCollection() { Id = 686, ParentTitle = "Customer69", Name = "Customer69 - Project 80", Customer = 421 },
                new ProjectCollection() { Id = 492, ParentTitle = "Customer70", Name = "Customer70 - Project 81", Customer = 232 },
                new ProjectCollection() { Id = 697, ParentTitle = "Customer71", Name = "Customer71 - Project 82", Customer = 432 },
                new ProjectCollection() { Id = 494, ParentTitle = "Customer72", Name = "Customer72 - Project 83", Customer = 225 },
                new ProjectCollection() { Id = 496, ParentTitle = "Customer73", Name = "Customer73 - Project 84", Customer = 380 },
                new ProjectCollection() { Id = 498, ParentTitle = "Customer74", Name = "Customer74 - Project 85", Customer = 233 },
                new ProjectCollection() { Id = 657, ParentTitle = "Customer74", Name = "Customer74 - Project 86", Customer = 233 },
                new ProjectCollection() { Id = 632, ParentTitle = "Customer74", Name = "Customer74 - Project 87", Customer = 233 },
                new ProjectCollection() { Id = 499, ParentTitle = "Customer75", Name = "Customer75 - Project 88", Customer = 234 },
                new ProjectCollection() { Id = 597, ParentTitle = "Customer177", Name = "Customer177 - Project 89", Customer = 292 },
                new ProjectCollection() { Id = 746, ParentTitle = "Customer76", Name = "Customer76 - Project 90", Customer = 477 },
                new ProjectCollection() { Id = 501, ParentTitle = "Customer77", Name = "Customer77 - Project 91", Customer = 236 },
                new ProjectCollection() { Id = 712, ParentTitle = "Customer78", Name = "Customer78 - Project 92", Customer = 447 },
                new ProjectCollection() { Id = 503, ParentTitle = "Customer79", Name = "Customer79 - Project 93", Customer = 226 },
                new ProjectCollection() { Id = 698, ParentTitle = "Customer81", Name = "Customer81 - Project 94", Customer = 433 },
                new ProjectCollection() { Id = 504, ParentTitle = "Customer82", Name = "Customer82 - Project 95", Customer = 227 },
                new ProjectCollection() { Id = 689, ParentTitle = "Customer83", Name = "Customer83 - Project 96", Customer = 424 },
                new ProjectCollection() { Id = 749, ParentTitle = "Customer83", Name = "Customer83 - Project 97", Customer = 424 },
                new ProjectCollection() { Id = 699, ParentTitle = "Customer84", Name = "Customer84 - Project 98", Customer = 434 },
                new ProjectCollection() { Id = 506, ParentTitle = "Customer85", Name = "Customer85 - Project 99", Customer = 239 },
                new ProjectCollection() { Id = 718, ParentTitle = "Customer86", Name = "Customer86 - Project 100", Customer = 453 },
                new ProjectCollection() { Id = 642, ParentTitle = "Customer87", Name = "Customer87 - Project 101", Customer = 408 },
                new ProjectCollection() { Id = 399, ParentTitle = "Customer88", Name = "Customer88 - Project 102", Customer = 381 },
                new ProjectCollection() { Id = 507, ParentTitle = "Customer88", Name = "Customer88 - Project 103", Customer = 381 },
                new ProjectCollection() { Id = 651, ParentTitle = "Customer90", Name = "Customer90 - Project 104", Customer = 2 },
                new ProjectCollection() { Id = 629, ParentTitle = "Customer90", Name = "Customer90 - Project 105", Customer = 2 },
                new ProjectCollection() { Id = 398, ParentTitle = "Customer90", Name = "Customer90 - Project 106", Customer = 2 },
                new ProjectCollection() { Id = 509, ParentTitle = "Customer90", Name = "Customer90 - Project 107", Customer = 2 },
                new ProjectCollection() { Id = 511, ParentTitle = "Customer92", Name = "Customer92 - Project 108", Customer = 242 },
                new ProjectCollection() { Id = 626, ParentTitle = "Customer93", Name = "Customer93 - Project 109", Customer = 402 },
                new ProjectCollection() { Id = 627, ParentTitle = "Customer94", Name = "Customer94 - Project 110", Customer = 403 },
                new ProjectCollection() { Id = 708, ParentTitle = "Customer95", Name = "Customer95 - Project 111", Customer = 443 },
                new ProjectCollection() { Id = 390, ParentTitle = "Customer91", Name = "Customer91 - Project 112", Customer = 1 },
                new ProjectCollection() { Id = 382, ParentTitle = "Customer91", Name = "Customer91 - Project 113", Customer = 1 },
                new ProjectCollection() { Id = 643, ParentTitle = "Customer96", Name = "Customer96 - Project 114", Customer = 409 },
                new ProjectCollection() { Id = 701, ParentTitle = "Customer97", Name = "Customer97 - Project 115", Customer = 435 },
                new ProjectCollection() { Id = 700, ParentTitle = "Customer97", Name = "Customer97 - Project 116", Customer = 435 },
                new ProjectCollection() { Id = 687, ParentTitle = "Customer98", Name = "Customer98 - Project 117", Customer = 422 },
                new ProjectCollection() { Id = 702, ParentTitle = "Customer99", Name = "Customer99 - Project 118", Customer = 436 },
                new ProjectCollection() { Id = 751, ParentTitle = "Customer100", Name = "Customer100 - Project 119", Customer = 481 },
                new ProjectCollection() { Id = 513, ParentTitle = "Customer101", Name = "Customer101 - Project 120", Customer = 243 },
                new ProjectCollection() { Id = 514, ParentTitle = "Customer102", Name = "Customer102 - Project 121", Customer = 244 },
                new ProjectCollection() { Id = 516, ParentTitle = "Customer103", Name = "Customer103 - Project 122", Customer = 245 },
                new ProjectCollection() { Id = 517, ParentTitle = "Customer104", Name = "Customer104 - Project 123", Customer = 246 },
                new ProjectCollection() { Id = 722, ParentTitle = "Customer105", Name = "Customer105 - Project 124", Customer = 457 },
                new ProjectCollection() { Id = 519, ParentTitle = "Customer106", Name = "Customer106 - Project 125", Customer = 400 },
                new ProjectCollection() { Id = 644, ParentTitle = "Customer107", Name = "Customer107 - Project 126", Customer = 410 },
                new ProjectCollection() { Id = 521, ParentTitle = "Customer108", Name = "Customer108 - Project 127", Customer = 248 },
                new ProjectCollection() { Id = 523, ParentTitle = "Customer109", Name = "Customer109 - Project 128", Customer = 249 },
                new ProjectCollection() { Id = 525, ParentTitle = "Customer110", Name = "Customer110 - Project 129", Customer = 247 },
                new ProjectCollection() { Id = 526, ParentTitle = "Customer111", Name = "Customer111 - Project 130", Customer = 250 },
                new ProjectCollection() { Id = 528, ParentTitle = "Customer112", Name = "Customer112 - Project 131", Customer = 251 },
                new ProjectCollection() { Id = 530, ParentTitle = "Customer113", Name = "Customer113 - Project 132", Customer = 252 },
                new ProjectCollection() { Id = 532, ParentTitle = "Customer114", Name = "Customer114 - Project 133", Customer = 253 },
                new ProjectCollection() { Id = 533, ParentTitle = "Customer115", Name = "Customer115 - Project 134", Customer = 257 },
                new ProjectCollection() { Id = 535, ParentTitle = "Customer116", Name = "Customer116 - Project 135", Customer = 258 },
                new ProjectCollection() { Id = 537, ParentTitle = "Customer117", Name = "Customer117 - Project 136", Customer = 259 },
                new ProjectCollection() { Id = 396, ParentTitle = "Customer91", Name = "Customer91 - Project 137", Customer = 1 },
                new ProjectCollection() { Id = 395, ParentTitle = "Customer91", Name = "Customer91 - Project 138", Customer = 1 },
                new ProjectCollection() { Id = 397, ParentTitle = "Customer91", Name = "Customer91 - Project 139", Customer = 1 },
                new ProjectCollection() { Id = 538, ParentTitle = "Customer118", Name = "Customer118 - Project 140", Customer = 260 },
                new ProjectCollection() { Id = 729, ParentTitle = "Customer119", Name = "Customer119 - Project 141", Customer = 465 },
                new ProjectCollection() { Id = 691, ParentTitle = "Customer120", Name = "Customer120 - Project 142", Customer = 427 },
                new ProjectCollection() { Id = 592, ParentTitle = "Customer121", Name = "Customer121 - Project 143", Customer = 382 },
                new ProjectCollection() { Id = 680, ParentTitle = "Customer122", Name = "Customer122 - Project 144", Customer = 438 },
                new ProjectCollection() { Id = 540, ParentTitle = "Customer123", Name = "Customer123 - Project 145", Customer = 261 },
                new ProjectCollection() { Id = 728, ParentTitle = "Customer124", Name = "Customer124 - Project 146", Customer = 464 },
                new ProjectCollection() { Id = 542, ParentTitle = "Customer125", Name = "Customer125 - Project 147", Customer = 254 },
                new ProjectCollection() { Id = 543, ParentTitle = "Customer126", Name = "Customer126 - Project 148", Customer = 255 },
                new ProjectCollection() { Id = 704, ParentTitle = "Customer127", Name = "Customer127 - Project 149", Customer = 439 },
                new ProjectCollection() { Id = 727, ParentTitle = "Customer128", Name = "Customer128 - Project 150", Customer = 463 },
                new ProjectCollection() { Id = 724, ParentTitle = "Customer129", Name = "Customer129 - Project 151", Customer = 460 },
                new ProjectCollection() { Id = 545, ParentTitle = "Customer130", Name = "Customer130 - Project 152", Customer = 262 },
                new ProjectCollection() { Id = 684, ParentTitle = "Customer131", Name = "Customer131 - Project 153", Customer = 479 },
                new ProjectCollection() { Id = 547, ParentTitle = "Customer132", Name = "Customer132 - Project 154", Customer = 263 },
                new ProjectCollection() { Id = 745, ParentTitle = "Customer133", Name = "Customer133 - Project 155", Customer = 476 },
                new ProjectCollection() { Id = 548, ParentTitle = "Customer134", Name = "Customer134 - Project 156", Customer = 265 },
                new ProjectCollection() { Id = 682, ParentTitle = "Customer135", Name = "Customer135 - Project 157", Customer = 440 },
                new ProjectCollection() { Id = 637, ParentTitle = "Customer136", Name = "Customer136 - Project 158", Customer = 404 },
                new ProjectCollection() { Id = 638, ParentTitle = "Customer136", Name = "Customer136 - Project 159", Customer = 404 },
                new ProjectCollection() { Id = 550, ParentTitle = "Customer137", Name = "Customer137 - Project 160", Customer = 266 },
                new ProjectCollection() { Id = 654, ParentTitle = "Customer138", Name = "Customer138 - Project 161", Customer = 267 },
                new ProjectCollection() { Id = 552, ParentTitle = "Customer138", Name = "Customer138 - Project 162", Customer = 267 },
                new ProjectCollection() { Id = 553, ParentTitle = "Customer139", Name = "Customer139 - Project 163", Customer = 268 },
                new ProjectCollection() { Id = 417, ParentTitle = "Customer140", Name = "Customer140 - Project 164", Customer = 389 },
                new ProjectCollection() { Id = 555, ParentTitle = "Customer140", Name = "Customer140 - Project 165", Customer = 389 },
                new ProjectCollection() { Id = 557, ParentTitle = "Customer141", Name = "Customer141 - Project 166", Customer = 269 },
                new ProjectCollection() { Id = 558, ParentTitle = "Customer142", Name = "Customer142 - Project 167", Customer = 270 },
                new ProjectCollection() { Id = 723, ParentTitle = "Customer143", Name = "Customer143 - Project 168", Customer = 458 },
                new ProjectCollection() { Id = 412, ParentTitle = "Customer144", Name = "Customer144 - Project 169", Customer = 274 },
                new ProjectCollection() { Id = 560, ParentTitle = "Customer144", Name = "Customer144 - Project 170", Customer = 274 },
                new ProjectCollection() { Id = 562, ParentTitle = "Customer145", Name = "Customer145 - Project 171", Customer = 377 },
                new ProjectCollection() { Id = 739, ParentTitle = "Customer146", Name = "Customer146 - Project 172", Customer = 459 },
                new ProjectCollection() { Id = 563, ParentTitle = "Customer147", Name = "Customer147 - Project 173", Customer = 275 },
                new ProjectCollection() { Id = 565, ParentTitle = "Customer148", Name = "Customer148 - Project 174", Customer = 276 },
                new ProjectCollection() { Id = 567, ParentTitle = "Customer148", Name = "Customer148 - Project 174", Customer = 276 },
                new ProjectCollection() { Id = 706, ParentTitle = "Customer150", Name = "Customer150 - Project 176", Customer = 441 },
                new ProjectCollection() { Id = 705, ParentTitle = "Customer150", Name = "Customer150 - Project 177", Customer = 441 },
                new ProjectCollection() { Id = 725, ParentTitle = "CustomerDupeProj1", Name = "Project duplicate", Customer = 461 },
                new ProjectCollection() { Id = 569, ParentTitle = "CustomerDupeProj2", Name = "Project duplicate", Customer = 271 },
                new ProjectCollection() { Id = 570, ParentTitle = "Customer153", Name = "Customer153 - Project 180", Customer = 272 },
                new ProjectCollection() { Id = 685, ParentTitle = "Customer154", Name = "Customer154 - Project 181", Customer = 420 },
                new ProjectCollection() { Id = 572, ParentTitle = "Customer155", Name = "Customer155 - Project 182", Customer = 278 },
                new ProjectCollection() { Id = 574, ParentTitle = "Customer156", Name = "Customer156 - Project 183", Customer = 273 },
                new ProjectCollection() { Id = 646, ParentTitle = "Customer156", Name = "Customer156 - Project 184", Customer = 273 },
                new ProjectCollection() { Id = 758, ParentTitle = "Customer157", Name = "Customer157 - Project 185", Customer = 489 },
                new ProjectCollection() { Id = 653, ParentTitle = "Customer158", Name = "Customer158 - Project 186", Customer = 280 },
                new ProjectCollection() { Id = 576, ParentTitle = "Customer158", Name = "Customer158 - Project 187", Customer = 280 },
                new ProjectCollection() { Id = 578, ParentTitle = "Customer159", Name = "Customer159 - Project 188", Customer = 281 },
                new ProjectCollection() { Id = 764, ParentTitle = "Customer160", Name = "Customer160 - Project 189", Customer = 494 },
                new ProjectCollection() { Id = 665, ParentTitle = "Customer161", Name = "Customer161 - Project 190", Customer = 415 },
                new ProjectCollection() { Id = 666, ParentTitle = "Customer161", Name = "Customer161 - Project 191", Customer = 415 },
                new ProjectCollection() { Id = 427, ParentTitle = "Customer162", Name = "Customer162 - Project 192", Customer = 399 },
                new ProjectCollection() { Id = 579, ParentTitle = "Customer162", Name = "Customer162 - Project 193", Customer = 399 },
                new ProjectCollection() { Id = 581, ParentTitle = "Customer163", Name = "Customer163 - Project 194", Customer = 282 },
                new ProjectCollection() { Id = 582, ParentTitle = "Customer164", Name = "Customer164 - Project 195", Customer = 283 },
                new ProjectCollection() { Id = 631, ParentTitle = "Customer93", Name = "Customer93 - Project 196", Customer = 402 },
                new ProjectCollection() { Id = 403, ParentTitle = "Customer165", Name = "Customer165 - Project 197", Customer = 201 },
                new ProjectCollection() { Id = 437, ParentTitle = "Customer165", Name = "Customer165 - Project 198", Customer = 201 },
                new ProjectCollection() { Id = 584, ParentTitle = "Customer166", Name = "Customer166 - Project 199", Customer = 287 },
                new ProjectCollection() { Id = 586, ParentTitle = "Customer167", Name = "Customer167 - Project 200", Customer = 284 },
                new ProjectCollection() { Id = 587, ParentTitle = "Customer168", Name = "Customer168 - Project 201", Customer = 285 },
                new ProjectCollection() { Id = 589, ParentTitle = "Customer169", Name = "Customer169 - Project 202", Customer = 288 },
                new ProjectCollection() { Id = 765, ParentTitle = "Customer170", Name = "Customer170 - Project 203", Customer = 495 },
                new ProjectCollection() { Id = 731, ParentTitle = "Customer171", Name = "Customer171 - Project 204", Customer = 467 },
                new ProjectCollection() { Id = 591, ParentTitle = "Customer172", Name = "Customer172 - Project 205", Customer = 289 },
                new ProjectCollection() { Id = 593, ParentTitle = "Customer173", Name = "Customer173 - Project 206", Customer = 290 },
                new ProjectCollection() { Id = 595, ParentTitle = "Customer174", Name = "Customer174 - Project 207", Customer = 291 },
                new ProjectCollection() { Id = 774, ParentTitle = "Customer175", Name = "Customer175 - Project 208", Customer = 500 },
                new ProjectCollection() { Id = 596, ParentTitle = "Customer176", Name = "Customer176 - Project 209", Customer = 286 },
                new ProjectCollection() { Id = 599, ParentTitle = "Customer178", Name = "Customer178 - Project 210", Customer = 293 },
                new ProjectCollection() { Id = 601, ParentTitle = "Customer179", Name = "Customer179 - Project 211", Customer = 294 },
                new ProjectCollection() { Id = 709, ParentTitle = "Customer180", Name = "Customer180 - Project 212", Customer = 444 },
                new ProjectCollection() { Id = 409, ParentTitle = "Customer181", Name = "Customer181 - Project 213", Customer = 295 },
                new ProjectCollection() { Id = 603, ParentTitle = "Customer181", Name = "Customer181 - Project 214", Customer = 295 },
                new ProjectCollection() { Id = 604, ParentTitle = "Customer182", Name = "Customer182 - Project 215", Customer = 299 },
                new ProjectCollection() { Id = 401, ParentTitle = "Customer183", Name = "Customer183 - Project 216", Customer = 300 },
                new ProjectCollection() { Id = 606, ParentTitle = "Customer183", Name = "Customer183 - Project 217", Customer = 300 },
                new ProjectCollection() { Id = 710, ParentTitle = "Customer184", Name = "Customer184 - Project 218", Customer = 445 },
                new ProjectCollection() { Id = 780, ParentTitle = "Customer185", Name = "Customer185 - Project 219", Customer = 505 },
                new ProjectCollection() { Id = 608, ParentTitle = "Customer186", Name = "Customer186 - Project 220", Customer = 301 },
                new ProjectCollection() { Id = 711, ParentTitle = "Customer187", Name = "Customer187 - Project 221", Customer = 446 },
                new ProjectCollection() { Id = 660, ParentTitle = "Customer188", Name = "Customer188 - Project 222", Customer = 405 },
                new ProjectCollection() { Id = 639, ParentTitle = "Customer188", Name = "Customer188 - Project 223", Customer = 405 },
                new ProjectCollection() { Id = 609, ParentTitle = "Customer189", Name = "Customer189 - Project 224", Customer = 296 },
                new ProjectCollection() { Id = 611, ParentTitle = "Customer190", Name = "Customer190 - Project 225", Customer = 302 },
                new ProjectCollection() { Id = 613, ParentTitle = "Customer191", Name = "Customer191 - Project 226", Customer = 297 },
                new ProjectCollection() { Id = 615, ParentTitle = "Customer192", Name = "Customer192 - Project 227", Customer = 298 },
                new ProjectCollection() { Id = 733, ParentTitle = "Customer193", Name = "Customer193 - Project 228", Customer = 469 },
                new ProjectCollection() { Id = 426, ParentTitle = "Customer194", Name = "Customer194 - Project 229", Customer = 398 },
                new ProjectCollection() { Id = 616, ParentTitle = "Customer194", Name = "Customer194 - Project 230", Customer = 398 },
                new ProjectCollection() { Id = 744, ParentTitle = "Customer195", Name = "Customer195 - Project 231", Customer = 475 },
                new ProjectCollection() { Id = 402, ParentTitle = "Customer196", Name = "Customer196 - Project 232", Customer = 383 },
                new ProjectCollection() { Id = 618, ParentTitle = "Customer196", Name = "Customer196 - Project 233", Customer = 383 },
                new ProjectCollection() { Id = 420, ParentTitle = "Customer197", Name = "Customer197 - Project 234", Customer = 392 },
                new ProjectCollection() { Id = 620, ParentTitle = "Customer197", Name = "Customer197 - Project 235", Customer = 392 },
                new ProjectCollection() { Id = 645, ParentTitle = "Customer198", Name = "Customer198 - Project 236", Customer = 411 },
                new ProjectCollection() { Id = 621, ParentTitle = "Customer199", Name = "Customer199 - Project 237", Customer = 304 },
                new ProjectCollection() { Id = 414, ParentTitle = "Customer199", Name = "Customer199 - Project 238", Customer = 304 },
                new ProjectCollection() { Id = 623, ParentTitle = "Customer200", Name = "Customer200 - Project 239", Customer = 305 },
                new ProjectCollection() { Id = 408, ParentTitle = "Customer201", Name = "Customer201 - Project 240", Customer = 306 },
                new ProjectCollection() { Id = 625, ParentTitle = "Customer201", Name = "Customer201 - Project 241", Customer = 306 },
                new ProjectCollection() { Id = 391, ParentTitle = "Customer201", Name = "Customer201 - Project 242", Customer = 306 },
                new ProjectCollection() { Id = 624, ParentTitle = "Customer202", Name = "Customer202 - Project 243", Customer = 307 },
                new ProjectCollection() { Id = 692, ParentTitle = "Customer203", Name = "Customer203 - Project 244", Customer = 428 },
                new ProjectCollection() { Id = 622, ParentTitle = "Customer204", Name = "Customer204 - Project 245", Customer = 308 },
                new ProjectCollection() { Id = 619, ParentTitle = "Customer205", Name = "Customer205 - Project 246", Customer = 310 },
                new ProjectCollection() { Id = 713, ParentTitle = "Customer206", Name = "Customer206 - Project 247", Customer = 448 },
                new ProjectCollection() { Id = 415, ParentTitle = "Customer207", Name = "Customer207 - Project 248", Customer = 387 },
                new ProjectCollection() { Id = 617, ParentTitle = "Customer207", Name = "Customer207 - Project 249", Customer = 387 },
                new ProjectCollection() { Id = 614, ParentTitle = "Customer208", Name = "Customer208 - Project 250", Customer = 309 },
                new ProjectCollection() { Id = 612, ParentTitle = "Customer209", Name = "Customer209 - Project 251", Customer = 311 },
                new ProjectCollection() { Id = 413, ParentTitle = "Customer210", Name = "Customer210 - Project 252", Customer = 312 },
                new ProjectCollection() { Id = 610, ParentTitle = "Customer210", Name = "Customer210 - Project 253", Customer = 312 },
                new ProjectCollection() { Id = 648, ParentTitle = "Customer210", Name = "Customer210 - Project 254", Customer = 312 },
                new ProjectCollection() { Id = 607, ParentTitle = "Customer211", Name = "Customer211 - Project 255", Customer = 313 },
                new ProjectCollection() { Id = 605, ParentTitle = "Customer212", Name = "Customer212 - Project 256", Customer = 314 },
                new ProjectCollection() { Id = 602, ParentTitle = "Customer213", Name = "Customer213 - Project 257", Customer = 315 },
                new ProjectCollection() { Id = 600, ParentTitle = "Customer214", Name = "Customer214 - Project 258", Customer = 316 },
                new ProjectCollection() { Id = 598, ParentTitle = "Customer215", Name = "Customer215 - Project 259", Customer = 317 },
                new ProjectCollection() { Id = 594, ParentTitle = "Customer216", Name = "Customer216 - Project 260", Customer = 318 },
                new ProjectCollection() { Id = 590, ParentTitle = "Customer217", Name = "Customer217 - Project 261", Customer = 319 },
                new ProjectCollection() { Id = 734, ParentTitle = "Customer218", Name = "Customer218 - Project 262", Customer = 470 },
                new ProjectCollection() { Id = 658, ParentTitle = "Customer219", Name = "Customer219 - Project 263", Customer = 414 },
                new ProjectCollection() { Id = 659, ParentTitle = "Customer219", Name = "Customer219 - Project 264", Customer = 414 },
                new ProjectCollection() { Id = 778, ParentTitle = "Customer221", Name = "Customer221 - Project 265", Customer = 503 },
                new ProjectCollection() { Id = 588, ParentTitle = "Customer222", Name = "Customer222 - Project 266", Customer = 322 },
                new ProjectCollection() { Id = 585, ParentTitle = "Customer223", Name = "Customer223 - Project 267", Customer = 320 },
                new ProjectCollection() { Id = 779, ParentTitle = "Customer224", Name = "Customer224 - Project 268", Customer = 504 },
                new ProjectCollection() { Id = 583, ParentTitle = "Customer225", Name = "Customer225 - Project 269", Customer = 323 },
                new ProjectCollection() { Id = 580, ParentTitle = "Customer226", Name = "Customer226 - Project 270", Customer = 326 },
                new ProjectCollection() { Id = 750, ParentTitle = "Customer227", Name = "Customer227 - Project 271", Customer = 480 },
                new ProjectCollection() { Id = 577, ParentTitle = "Customer228", Name = "Customer228 - Project 272", Customer = 327 },
                new ProjectCollection() { Id = 575, ParentTitle = "Customer229", Name = "Customer229 - Project 273", Customer = 324 },
                new ProjectCollection() { Id = 738, ParentTitle = "Customer230", Name = "Customer230 - Project 274", Customer = 426 },
                new ProjectCollection() { Id = 772, ParentTitle = "Customer231", Name = "Customer231 - Project 275", Customer = 325 },
                new ProjectCollection() { Id = 573, ParentTitle = "Customer231", Name = "Customer231 - Project 276", Customer = 325 },
                new ProjectCollection() { Id = 571, ParentTitle = "Customer232", Name = "Customer232 - Project 277", Customer = 329 },
                new ProjectCollection() { Id = 568, ParentTitle = "Customer233", Name = "Customer233 - Project 278", Customer = 330 },
                new ProjectCollection() { Id = 775, ParentTitle = "Customer234", Name = "Customer234 - Project 279", Customer = 501 },
                new ProjectCollection() { Id = 388, ParentTitle = "Customer91", Name = "Customer91 - Project 280", Customer = 1 },
                new ProjectCollection() { Id = 1, ParentTitle = "Customer91", Name = "Customer91 - Project 281", Customer = 1 },
                new ProjectCollection() { Id = 6, ParentTitle = "Customer91", Name = "Customer91 - Project 282", Customer = 1 },
                new ProjectCollection() { Id = 5, ParentTitle = "Customer91", Name = "Customer91 - Project 283", Customer = 1 },
                new ProjectCollection() { Id = 8, ParentTitle = "Customer91", Name = "Customer91 - Project 284", Customer = 1 },
                new ProjectCollection() { Id = 3, ParentTitle = "Customer91", Name = "Customer91 - Project 285", Customer = 1 },
                new ProjectCollection() { Id = 4, ParentTitle = "Customer91", Name = "Customer91 - Project 286", Customer = 1 },
                new ProjectCollection() { Id = 2, ParentTitle = "Customer91", Name = "Customer91 - Project 287", Customer = 1 },
                new ProjectCollection() { Id = 633, ParentTitle = "Customer93", Name = "Customer93 - Project 288", Customer = 402 },
                new ProjectCollection() { Id = 404, ParentTitle = "Customer89", Name = "Customer89 - Project 289", Customer = 3 },
                new ProjectCollection() { Id = 7, ParentTitle = "Customer89", Name = "Customer89 - Project 290", Customer = 3 },
                new ProjectCollection() { Id = 393, ParentTitle = "Customer90", Name = "Customer90 - Project 291", Customer = 2 },
                new ProjectCollection() { Id = 566, ParentTitle = "Customer235", Name = "Customer235 - Project 292", Customer = 331 },
                new ProjectCollection() { Id = 564, ParentTitle = "Customer236", Name = "Customer236 - Project 293", Customer = 332 },
                new ProjectCollection() { Id = 561, ParentTitle = "Customer237", Name = "Customer237 - Project 294", Customer = 334 },
                new ProjectCollection() { Id = 559, ParentTitle = "Customer238", Name = "Customer238 - Project 295", Customer = 335 },
                new ProjectCollection() { Id = 556, ParentTitle = "Customer239", Name = "Customer239 - Project 296", Customer = 336 },
                new ProjectCollection() { Id = 554, ParentTitle = "Customer240", Name = "Customer240 - Project 297", Customer = 337 },
                new ProjectCollection() { Id = 551, ParentTitle = "Customer241", Name = "Customer241 - Project 298", Customer = 338 },
                new ProjectCollection() { Id = 549, ParentTitle = "Customer242", Name = "Customer242 - Project 299", Customer = 339 },
                new ProjectCollection() { Id = 546, ParentTitle = "Customer243", Name = "Customer243 - Project 300", Customer = 340 },
                new ProjectCollection() { Id = 544, ParentTitle = "Customer244", Name = "Customer244 - Project 301", Customer = 341 },
                new ProjectCollection() { Id = 400, ParentTitle = "Customer245", Name = "Customer245 - Project 302", Customer = 384 },
                new ProjectCollection() { Id = 541, ParentTitle = "Customer245", Name = "Customer245 - Project 303", Customer = 384 },
                new ProjectCollection() { Id = 652, ParentTitle = "Customer246", Name = "Customer246 - Project 304", Customer = 342 },
                new ProjectCollection() { Id = 539, ParentTitle = "Customer246", Name = "Customer246 - Project 305", Customer = 342 },
                new ProjectCollection() { Id = 536, ParentTitle = "Customer247", Name = "Customer247 - Project 306", Customer = 333 },
                new ProjectCollection() { Id = 534, ParentTitle = "Customer248", Name = "Customer248 - Project 307", Customer = 343 },
                new ProjectCollection() { Id = 759, ParentTitle = "Customer250", Name = "Customer250 - Project 308", Customer = 491 },
                new ProjectCollection() { Id = 531, ParentTitle = "Customer251", Name = "Customer251 - Project 309", Customer = 390 },
                new ProjectCollection() { Id = 418, ParentTitle = "Customer251", Name = "Customer251 - Project 310", Customer = 390 },
                new ProjectCollection() { Id = 529, ParentTitle = "Customer252", Name = "Customer252 - Project 311", Customer = 344 },
                new ProjectCollection() { Id = 527, ParentTitle = "Customer253", Name = "Customer253 - Project 312", Customer = 345 },
                new ProjectCollection() { Id = 747, ParentTitle = "Customer254", Name = "Customer254 - Project 313", Customer = 359 },
                new ProjectCollection() { Id = 524, ParentTitle = "Customer254", Name = "Customer254 - Project 314", Customer = 359 },
                new ProjectCollection() { Id = 781, ParentTitle = "Customer255", Name = "Customer255 - Project 315", Customer = 506 },
                new ProjectCollection() { Id = 721, ParentTitle = "Customer256", Name = "Customer256 - Project 316", Customer = 456 },
                new ProjectCollection() { Id = 522, ParentTitle = "Customer257", Name = "Customer257 - Project 317", Customer = 349 },
                new ProjectCollection() { Id = 707, ParentTitle = "Customer258", Name = "Customer258 - Project 318", Customer = 442 },
                new ProjectCollection() { Id = 714, ParentTitle = "Customer259", Name = "Customer259 - Project 319", Customer = 449 },
                new ProjectCollection() { Id = 520, ParentTitle = "Customer260", Name = "Customer260 - Project 320", Customer = 346 },
                new ProjectCollection() { Id = 518, ParentTitle = "Customer261", Name = "Customer261 - Project 321", Customer = 350 },
                new ProjectCollection() { Id = 515, ParentTitle = "Customer262", Name = "Customer262 - Project 322", Customer = 192 },
                new ProjectCollection() { Id = 730, ParentTitle = "Customer263", Name = "Customer263 - Project 323", Customer = 466 },
                new ProjectCollection() { Id = 512, ParentTitle = "Customer264", Name = "Customer264 - Project 324", Customer = 351 },
                new ProjectCollection() { Id = 703, ParentTitle = "Customer265", Name = "Customer265 - Project 325", Customer = 437 },
                new ProjectCollection() { Id = 510, ParentTitle = "Customer266", Name = "Customer266 - Project 326", Customer = 352 },
                new ProjectCollection() { Id = 768, ParentTitle = "Customer267", Name = "Customer267 - Project 327", Customer = 353 },
                new ProjectCollection() { Id = 508, ParentTitle = "Customer267", Name = "Customer267 - Project 328", Customer = 353 },
                new ProjectCollection() { Id = 505, ParentTitle = "Customer268", Name = "Customer268 - Project 329", Customer = 354 },
                new ProjectCollection() { Id = 760, ParentTitle = "Customer269", Name = "Customer269 - Project 330", Customer = 492 },
                new ProjectCollection() { Id = 502, ParentTitle = "Customer270", Name = "Customer270 - Project 331", Customer = 348 },
                new ProjectCollection() { Id = 735, ParentTitle = "Customer271", Name = "Customer271 - Project 332", Customer = 473 },
                new ProjectCollection() { Id = 715, ParentTitle = "Customer272", Name = "Customer272 - Project 333", Customer = 450 },
                new ProjectCollection() { Id = 500, ParentTitle = "Customer273", Name = "Customer273 - Project 334", Customer = 355 },
                new ProjectCollection() { Id = 497, ParentTitle = "Customer274", Name = "Customer274 - Project 335", Customer = 356 },
                new ProjectCollection() { Id = 495, ParentTitle = "Customer275", Name = "Customer275 - Project 336", Customer = 357 },
                new ProjectCollection() { Id = 493, ParentTitle = "Customer276", Name = "Customer276 - Project 337", Customer = 358 },
                new ProjectCollection() { Id = 766, ParentTitle = "Customer277", Name = "Customer277 - Project 338", Customer = 496 },
                new ProjectCollection() { Id = 655, ParentTitle = "Customer278", Name = "Customer278 - Project 339", Customer = 413 },
                new ProjectCollection() { Id = 656, ParentTitle = "Customer278", Name = "Customer278 - Project 340", Customer = 413 },
                new ProjectCollection() { Id = 773, ParentTitle = "Customer279", Name = "Customer279 - Project 341", Customer = 499 },
                new ProjectCollection() { Id = 490, ParentTitle = "Customer280", Name = "Customer280 - Project 342", Customer = 362 },
                new ProjectCollection() { Id = 488, ParentTitle = "Customer281", Name = "Customer281 - Project 343", Customer = 360 },
                new ProjectCollection() { Id = 486, ParentTitle = "Customer282", Name = "Customer282 - Project 344", Customer = 363 },
                new ProjectCollection() { Id = 484, ParentTitle = "Customer283", Name = "Customer283 - Project 345", Customer = 364 },
                new ProjectCollection() { Id = 424, ParentTitle = "Customer284", Name = "Customer284 - Project 346", Customer = 396 },
                new ProjectCollection() { Id = 482, ParentTitle = "Customer284", Name = "Customer284 - Project 347", Customer = 396 },
                new ProjectCollection() { Id = 741, ParentTitle = "Customer285", Name = "Customer285 - Project 348", Customer = 472 },
                new ProjectCollection() { Id = 716, ParentTitle = "Customer286", Name = "Customer286 - Project 349", Customer = 451 },
                new ProjectCollection() { Id = 479, ParentTitle = "Customer287", Name = "Customer287 - Project 350", Customer = 361 },
                new ProjectCollection() { Id = 719, ParentTitle = "Customer288", Name = "Customer288 - Project 351", Customer = 454 },
                new ProjectCollection() { Id = 477, ParentTitle = "Customer289", Name = "Customer289 - Project 352", Customer = 366 },
                new ProjectCollection() { Id = 474, ParentTitle = "Customer290", Name = "Customer290 - Project 353", Customer = 367 },
                new ProjectCollection() { Id = 736, ParentTitle = "Customer291", Name = "Customer291 - Project 354", Customer = 478 },
                new ProjectCollection() { Id = 472, ParentTitle = "Customer292", Name = "Customer292 - Project 355", Customer = 368 },
                new ProjectCollection() { Id = 771, ParentTitle = "Customer293", Name = "Customer293 - Project 356", Customer = 370 },
                new ProjectCollection() { Id = 470, ParentTitle = "Customer293", Name = "Customer293 - Project 357", Customer = 370 },
                new ProjectCollection() { Id = 755, ParentTitle = "Customer293", Name = "Customer293 - Project 358", Customer = 370 },
                new ProjectCollection() { Id = 406, ParentTitle = "Customer294", Name = "Customer294 - Project 359", Customer = 369 },
                new ProjectCollection() { Id = 468, ParentTitle = "Customer294", Name = "Customer294 - Project 360", Customer = 369 },
                new ProjectCollection() { Id = 465, ParentTitle = "Customer295", Name = "Customer295 - Project 361", Customer = 371 },
                new ProjectCollection() { Id = 762, ParentTitle = "Customer296", Name = "Customer296 - Project 362", Customer = 423 },
                new ProjectCollection() { Id = 688, ParentTitle = "Customer296", Name = "Customer296 - Project 363", Customer = 423 },
                new ProjectCollection() { Id = 763, ParentTitle = "Customer296", Name = "Customer296 - Project 364", Customer = 423 },
                new ProjectCollection() { Id = 425, ParentTitle = "Customer297", Name = "Customer297 - Project 365", Customer = 397 },
                new ProjectCollection() { Id = 462, ParentTitle = "Customer297", Name = "Customer297 - Project 366", Customer = 397 },
                new ProjectCollection() { Id = 459, ParentTitle = "Customer298", Name = "Customer298 - Project 367", Customer = 374 },
                new ProjectCollection() { Id = 456, ParentTitle = "Customer299", Name = "Customer299 - Project 368", Customer = 372 },
                new ProjectCollection() { Id = 694, ParentTitle = "Customer300", Name = "Customer300 - Project 369", Customer = 429 },
                new ProjectCollection() { Id = 452, ParentTitle = "Customer301", Name = "Customer301 - Project 370", Customer = 373 },
                new ProjectCollection() { Id = 410, ParentTitle = "Customer302", Name = "Customer302 - Project 371", Customer = 385 },
                new ProjectCollection() { Id = 449, ParentTitle = "Customer302", Name = "Customer302 - Project 372", Customer = 385 },
                new ProjectCollection() { Id = 447, ParentTitle = "Customer303", Name = "Customer303 - Project 373", Customer = 375 },
                new ProjectCollection() { Id = 445, ParentTitle = "Customer304", Name = "Customer304 - Project 374", Customer = 386 },
                new ProjectCollection() { Id = 752, ParentTitle = "Customer305", Name = "Customer305 - Project 375", Customer = 485 },
                new ProjectCollection() { Id = 761, ParentTitle = "Customer306", Name = "Customer306 - Project 376", Customer = 493 },
                new ProjectCollection() { Id = 756, ParentTitle = "Customer307", Name = "Customer307 - Project 377", Customer = 487 },
                new ProjectCollection() { Id = 442, ParentTitle = "Customer308", Name = "Customer308 - Project 378", Customer = 376 },
            };

            return await Task.FromResult(projects.ToList()).ConfigureAwait(false);
        }
#pragma warning disable MA0051 // Method is too long
        public async Task<IList<CustomerCollection>> GetCustomers()
#pragma warning restore MA0051 // Method is too long
        {
            var customers = new List<CustomerCollection>
            {
                new CustomerCollection() { Id = 1, Name = "Customer91" },
                new CustomerCollection() { Id = 2, Name = "Customer90" },
                new CustomerCollection() { Id = 3, Name = "Customer89" },
                new CustomerCollection() { Id = 190, Name = "CustomerDupeProj" },
                new CustomerCollection() { Id = 192, Name = "Customer262" },
                new CustomerCollection() { Id = 194, Name = "Customer10" },
                new CustomerCollection() { Id = 195, Name = "Customer15" },
                new CustomerCollection() { Id = 196, Name = "Customer25" },
                new CustomerCollection() { Id = 197, Name = "Customer33" },
                new CustomerCollection() { Id = 198, Name = "Customer8" },
                new CustomerCollection() { Id = 199, Name = "Customer11" },
                new CustomerCollection() { Id = 200, Name = "Customer16" },
                new CustomerCollection() { Id = 201, Name = "Customer165" },
                new CustomerCollection() { Id = 202, Name = "Customer19" },
                new CustomerCollection() { Id = 203, Name = "Customer20" },
                new CustomerCollection() { Id = 204, Name = "Customer21" },
                new CustomerCollection() { Id = 205, Name = "Customer24" },
                new CustomerCollection() { Id = 206, Name = "Customer26" },
                new CustomerCollection() { Id = 207, Name = "Customer29" },
                new CustomerCollection() { Id = 208, Name = "Customer31" },
                new CustomerCollection() { Id = 209, Name = "Customer32" },
                new CustomerCollection() { Id = 210, Name = "Customer44" },
                new CustomerCollection() { Id = 211, Name = "Customer43" },
                new CustomerCollection() { Id = 212, Name = "Customer45" },
                new CustomerCollection() { Id = 213, Name = "Customer37" },
                new CustomerCollection() { Id = 214, Name = "Customer38" },
                new CustomerCollection() { Id = 215, Name = "Customer39" },
                new CustomerCollection() { Id = 216, Name = "Customer41" },
                new CustomerCollection() { Id = 217, Name = "Customer42" },
                new CustomerCollection() { Id = 218, Name = "Customer48" },
                new CustomerCollection() { Id = 219, Name = "Customer49" },
                new CustomerCollection() { Id = 220, Name = "Customer50" },
                new CustomerCollection() { Id = 221, Name = "Customer54" },
                new CustomerCollection() { Id = 222, Name = "Customer55" },
                new CustomerCollection() { Id = 223, Name = "Customer56" },
                new CustomerCollection() { Id = 224, Name = "Customer57" },
                new CustomerCollection() { Id = 225, Name = "Customer72" },
                new CustomerCollection() { Id = 226, Name = "Customer79" },
                new CustomerCollection() { Id = 227, Name = "Customer82" },
                new CustomerCollection() { Id = 228, Name = "Customer63" },
                new CustomerCollection() { Id = 229, Name = "Customer66" },
                new CustomerCollection() { Id = 230, Name = "Customer67" },
                new CustomerCollection() { Id = 231, Name = "Customer68" },
                new CustomerCollection() { Id = 232, Name = "Customer70" },
                new CustomerCollection() { Id = 233, Name = "Customer74" },
                new CustomerCollection() { Id = 234, Name = "Customer75" },
                new CustomerCollection() { Id = 236, Name = "Customer77" },
                new CustomerCollection() { Id = 237, Name = "Customer80" },
                new CustomerCollection() { Id = 239, Name = "Customer85" },
                new CustomerCollection() { Id = 242, Name = "Customer92" },
                new CustomerCollection() { Id = 243, Name = "Customer101" },
                new CustomerCollection() { Id = 244, Name = "Customer102" },
                new CustomerCollection() { Id = 245, Name = "Customer103" },
                new CustomerCollection() { Id = 246, Name = "Customer104" },
                new CustomerCollection() { Id = 247, Name = "Customer110" },
                new CustomerCollection() { Id = 248, Name = "Customer108" },
                new CustomerCollection() { Id = 249, Name = "Customer109" },
                new CustomerCollection() { Id = 250, Name = "Customer111" },
                new CustomerCollection() { Id = 251, Name = "Customer112" },
                new CustomerCollection() { Id = 252, Name = "Customer113" },
                new CustomerCollection() { Id = 253, Name = "Customer114" },
                new CustomerCollection() { Id = 254, Name = "Customer125" },
                new CustomerCollection() { Id = 255, Name = "Customer126" },
                new CustomerCollection() { Id = 257, Name = "Customer115" },
                new CustomerCollection() { Id = 258, Name = "Customer116" },
                new CustomerCollection() { Id = 259, Name = "Customer117" },
                new CustomerCollection() { Id = 260, Name = "Customer118" },
                new CustomerCollection() { Id = 261, Name = "Customer123" },
                new CustomerCollection() { Id = 262, Name = "Customer130" },
                new CustomerCollection() { Id = 263, Name = "Customer132" },
                new CustomerCollection() { Id = 265, Name = "Customer134" },
                new CustomerCollection() { Id = 266, Name = "Customer137" },
                new CustomerCollection() { Id = 267, Name = "Customer138" },
                new CustomerCollection() { Id = 268, Name = "Customer139" },
                new CustomerCollection() { Id = 269, Name = "Customer141" },
                new CustomerCollection() { Id = 270, Name = "Customer142" },
                new CustomerCollection() { Id = 271, Name = "CustomerDupeProj2" },
                new CustomerCollection() { Id = 272, Name = "Customer153" },
                new CustomerCollection() { Id = 273, Name = "Customer156" },
                new CustomerCollection() { Id = 274, Name = "Customer144" },
                new CustomerCollection() { Id = 275, Name = "Customer147" },
                new CustomerCollection() { Id = 276, Name = "Customer148" },
                new CustomerCollection() { Id = 277, Name = "Customer149" },
                new CustomerCollection() { Id = 278, Name = "Customer155" },
                new CustomerCollection() { Id = 280, Name = "Customer158" },
                new CustomerCollection() { Id = 281, Name = "Customer159" },
                new CustomerCollection() { Id = 282, Name = "Customer163" },
                new CustomerCollection() { Id = 283, Name = "Customer164" },
                new CustomerCollection() { Id = 284, Name = "Customer167" },
                new CustomerCollection() { Id = 285, Name = "Customer168" },
                new CustomerCollection() { Id = 286, Name = "Customer176" },
                new CustomerCollection() { Id = 287, Name = "Customer166" },
                new CustomerCollection() { Id = 288, Name = "Customer169" },
                new CustomerCollection() { Id = 289, Name = "Customer172" },
                new CustomerCollection() { Id = 290, Name = "Customer173" },
                new CustomerCollection() { Id = 291, Name = "Customer174" },
                new CustomerCollection() { Id = 292, Name = "Customer177" },
                new CustomerCollection() { Id = 293, Name = "Customer178" },
                new CustomerCollection() { Id = 294, Name = "Customer179" },
                new CustomerCollection() { Id = 295, Name = "Customer181" },
                new CustomerCollection() { Id = 296, Name = "Customer189" },
                new CustomerCollection() { Id = 297, Name = "Customer191" },
                new CustomerCollection() { Id = 298, Name = "Customer192" },
                new CustomerCollection() { Id = 299, Name = "Customer182" },
                new CustomerCollection() { Id = 300, Name = "Customer183" },
                new CustomerCollection() { Id = 301, Name = "Customer186" },
                new CustomerCollection() { Id = 302, Name = "Customer190" },
                new CustomerCollection() { Id = 304, Name = "Customer199" },
                new CustomerCollection() { Id = 305, Name = "Customer200" },
                new CustomerCollection() { Id = 306, Name = "Customer201" },
                new CustomerCollection() { Id = 307, Name = "Customer202" },
                new CustomerCollection() { Id = 308, Name = "Customer204" },
                new CustomerCollection() { Id = 309, Name = "Customer208" },
                new CustomerCollection() { Id = 310, Name = "Customer205" },
                new CustomerCollection() { Id = 311, Name = "Customer209" },
                new CustomerCollection() { Id = 312, Name = "Customer210" },
                new CustomerCollection() { Id = 313, Name = "Customer211" },
                new CustomerCollection() { Id = 314, Name = "Customer212" },
                new CustomerCollection() { Id = 315, Name = "Customer213" },
                new CustomerCollection() { Id = 316, Name = "Customer214" },
                new CustomerCollection() { Id = 317, Name = "Customer215" },
                new CustomerCollection() { Id = 318, Name = "Customer216" },
                new CustomerCollection() { Id = 319, Name = "Customer217" },
                new CustomerCollection() { Id = 320, Name = "Customer223" },
                new CustomerCollection() { Id = 321, Name = "Customer220" },
                new CustomerCollection() { Id = 322, Name = "Customer222" },
                new CustomerCollection() { Id = 323, Name = "Customer225" },
                new CustomerCollection() { Id = 324, Name = "Customer229" },
                new CustomerCollection() { Id = 325, Name = "Customer231" },
                new CustomerCollection() { Id = 326, Name = "Customer226" },
                new CustomerCollection() { Id = 327, Name = "Customer228" },
                new CustomerCollection() { Id = 329, Name = "Customer232" },
                new CustomerCollection() { Id = 330, Name = "Customer233" },
                new CustomerCollection() { Id = 331, Name = "Customer235" },
                new CustomerCollection() { Id = 332, Name = "Customer236" },
                new CustomerCollection() { Id = 333, Name = "Customer247" },
                new CustomerCollection() { Id = 334, Name = "Customer237" },
                new CustomerCollection() { Id = 335, Name = "Customer238" },
                new CustomerCollection() { Id = 336, Name = "Customer239" },
                new CustomerCollection() { Id = 337, Name = "Customer240" },
                new CustomerCollection() { Id = 338, Name = "Customer241" },
                new CustomerCollection() { Id = 339, Name = "Customer242" },
                new CustomerCollection() { Id = 340, Name = "Customer243" },
                new CustomerCollection() { Id = 341, Name = "Customer244" },
                new CustomerCollection() { Id = 342, Name = "Customer246" },
                new CustomerCollection() { Id = 343, Name = "Customer248" },
                new CustomerCollection() { Id = 344, Name = "Customer252" },
                new CustomerCollection() { Id = 345, Name = "Customer253" },
                new CustomerCollection() { Id = 346, Name = "Customer260" },
                new CustomerCollection() { Id = 348, Name = "Customer270" },
                new CustomerCollection() { Id = 349, Name = "Customer257" },
                new CustomerCollection() { Id = 350, Name = "Customer261" },
                new CustomerCollection() { Id = 351, Name = "Customer264" },
                new CustomerCollection() { Id = 352, Name = "Customer266" },
                new CustomerCollection() { Id = 353, Name = "Customer267" },
                new CustomerCollection() { Id = 354, Name = "Customer268" },
                new CustomerCollection() { Id = 355, Name = "Customer273" },
                new CustomerCollection() { Id = 356, Name = "Customer274" },
                new CustomerCollection() { Id = 357, Name = "Customer275" },
                new CustomerCollection() { Id = 358, Name = "Customer276" },
                new CustomerCollection() { Id = 359, Name = "Customer254" },
                new CustomerCollection() { Id = 360, Name = "Customer281" },
                new CustomerCollection() { Id = 361, Name = "Customer287" },
                new CustomerCollection() { Id = 362, Name = "Customer280" },
                new CustomerCollection() { Id = 363, Name = "Customer282" },
                new CustomerCollection() { Id = 364, Name = "Customer283" },
                new CustomerCollection() { Id = 366, Name = "Customer289" },
                new CustomerCollection() { Id = 367, Name = "Customer290" },
                new CustomerCollection() { Id = 368, Name = "Customer292" },
                new CustomerCollection() { Id = 369, Name = "Customer294" },
                new CustomerCollection() { Id = 370, Name = "Customer293" },
                new CustomerCollection() { Id = 371, Name = "Customer295" },
                new CustomerCollection() { Id = 372, Name = "Customer299" },
                new CustomerCollection() { Id = 373, Name = "Customer301" },
                new CustomerCollection() { Id = 374, Name = "Customer298" },
                new CustomerCollection() { Id = 375, Name = "Customer303" },
                new CustomerCollection() { Id = 376, Name = "Customer308" },
                new CustomerCollection() { Id = 377, Name = "Customer145" },
                new CustomerCollection() { Id = 378, Name = "Customer18" },
                new CustomerCollection() { Id = 379, Name = "Customer23" },
                new CustomerCollection() { Id = 380, Name = "Customer73" },
                new CustomerCollection() { Id = 381, Name = "Customer88" },
                new CustomerCollection() { Id = 382, Name = "Customer121" },
                new CustomerCollection() { Id = 383, Name = "Customer196" },
                new CustomerCollection() { Id = 384, Name = "Customer245" },
                new CustomerCollection() { Id = 385, Name = "Customer302" },
                new CustomerCollection() { Id = 386, Name = "Customer304" },
                new CustomerCollection() { Id = 387, Name = "Customer207" },
                new CustomerCollection() { Id = 388, Name = "Customer17" },
                new CustomerCollection() { Id = 389, Name = "Customer140" },
                new CustomerCollection() { Id = 390, Name = "Customer251" },
                new CustomerCollection() { Id = 391, Name = "Customer28" },
                new CustomerCollection() { Id = 392, Name = "Customer197" },
                new CustomerCollection() { Id = 393, Name = "Customer14" },
                new CustomerCollection() { Id = 394, Name = "Customer36" },
                new CustomerCollection() { Id = 395, Name = "Customer13" },
                new CustomerCollection() { Id = 396, Name = "Customer284" },
                new CustomerCollection() { Id = 397, Name = "Customer297" },
                new CustomerCollection() { Id = 398, Name = "Customer194" },
                new CustomerCollection() { Id = 399, Name = "Customer162" },
                new CustomerCollection() { Id = 400, Name = "Customer106" },
                new CustomerCollection() { Id = 402, Name = "Customer93" },
                new CustomerCollection() { Id = 403, Name = "Customer94" },
                new CustomerCollection() { Id = 404, Name = "Customer136" },
                new CustomerCollection() { Id = 405, Name = "Customer188" },
                new CustomerCollection() { Id = 406, Name = "Customer22" },
                new CustomerCollection() { Id = 407, Name = "Customer64" },
                new CustomerCollection() { Id = 408, Name = "Customer87" },
                new CustomerCollection() { Id = 409, Name = "Customer96" },
                new CustomerCollection() { Id = 410, Name = "Customer107" },
                new CustomerCollection() { Id = 411, Name = "Customer198" },
                new CustomerCollection() { Id = 412, Name = "Customer27" },
                new CustomerCollection() { Id = 413, Name = "Customer278" },
                new CustomerCollection() { Id = 414, Name = "Customer219" },
                new CustomerCollection() { Id = 415, Name = "Customer161" },
                new CustomerCollection() { Id = 416, Name = "Customer46" },
                new CustomerCollection() { Id = 417, Name = "Customer52" },
                new CustomerCollection() { Id = 418, Name = "Customer59" },
                new CustomerCollection() { Id = 419, Name = "Customer62" },
                new CustomerCollection() { Id = 420, Name = "Customer154" },
                new CustomerCollection() { Id = 421, Name = "Customer69" },
                new CustomerCollection() { Id = 422, Name = "Customer98" },
                new CustomerCollection() { Id = 423, Name = "Customer296" },
                new CustomerCollection() { Id = 424, Name = "Customer83" },
                new CustomerCollection() { Id = 425, Name = "Customer51" },
                new CustomerCollection() { Id = 426, Name = "Customer230" },
                new CustomerCollection() { Id = 427, Name = "Customer120" },
                new CustomerCollection() { Id = 428, Name = "Customer203" },
                new CustomerCollection() { Id = 429, Name = "Customer300" },
                new CustomerCollection() { Id = 430, Name = "Customer60" },
                new CustomerCollection() { Id = 431, Name = "Customer40" },
                new CustomerCollection() { Id = 432, Name = "Customer71" },
                new CustomerCollection() { Id = 433, Name = "Customer81" },
                new CustomerCollection() { Id = 434, Name = "Customer84" },
                new CustomerCollection() { Id = 435, Name = "Customer97" },
                new CustomerCollection() { Id = 436, Name = "Customer99" },
                new CustomerCollection() { Id = 437, Name = "Customer265" },
                new CustomerCollection() { Id = 438, Name = "Customer122" },
                new CustomerCollection() { Id = 439, Name = "Customer127" },
                new CustomerCollection() { Id = 440, Name = "Customer135" },
                new CustomerCollection() { Id = 441, Name = "Customer150" },
                new CustomerCollection() { Id = 442, Name = "Customer258" },
                new CustomerCollection() { Id = 443, Name = "Customer95" },
                new CustomerCollection() { Id = 444, Name = "Customer180" },
                new CustomerCollection() { Id = 445, Name = "Customer184" },
                new CustomerCollection() { Id = 446, Name = "Customer187" },
                new CustomerCollection() { Id = 447, Name = "Customer78" },
                new CustomerCollection() { Id = 448, Name = "Customer206" },
                new CustomerCollection() { Id = 449, Name = "Customer259" },
                new CustomerCollection() { Id = 450, Name = "Customer272" },
                new CustomerCollection() { Id = 451, Name = "Customer286" },
                new CustomerCollection() { Id = 452, Name = "Customer35" },
                new CustomerCollection() { Id = 453, Name = "Customer86" },
                new CustomerCollection() { Id = 454, Name = "Customer288" },
                new CustomerCollection() { Id = 455, Name = "Customer65" },
                new CustomerCollection() { Id = 456, Name = "Customer256" },
                new CustomerCollection() { Id = 457, Name = "Customer105" },
                new CustomerCollection() { Id = 458, Name = "Customer143" },
                new CustomerCollection() { Id = 459, Name = "Customer146" },
                new CustomerCollection() { Id = 460, Name = "Customer129" },
                new CustomerCollection() { Id = 461, Name = "CustomerDupeProj1" },
                new CustomerCollection() { Id = 462, Name = "Customer61" },
                new CustomerCollection() { Id = 463, Name = "Customer128" },
                new CustomerCollection() { Id = 464, Name = "Customer124" },
                new CustomerCollection() { Id = 465, Name = "Customer119" },
                new CustomerCollection() { Id = 466, Name = "Customer263" },
                new CustomerCollection() { Id = 467, Name = "Customer171" },
                new CustomerCollection() { Id = 468, Name = "Customer9" },
                new CustomerCollection() { Id = 469, Name = "Customer193" },
                new CustomerCollection() { Id = 470, Name = "Customer218" },
                new CustomerCollection() { Id = 471, Name = "Customer12" },
                new CustomerCollection() { Id = 472, Name = "Customer285" },
                new CustomerCollection() { Id = 473, Name = "Customer271" },
                new CustomerCollection() { Id = 474, Name = "Customer53" },
                new CustomerCollection() { Id = 475, Name = "Customer195" },
                new CustomerCollection() { Id = 476, Name = "Customer133" },
                new CustomerCollection() { Id = 477, Name = "Customer76" },
                new CustomerCollection() { Id = 478, Name = "Customer291" },
                new CustomerCollection() { Id = 479, Name = "Customer131" },
                new CustomerCollection() { Id = 480, Name = "Customer227" },
                new CustomerCollection() { Id = 481, Name = "Customer100" },
                new CustomerCollection() { Id = 482, Name = "Customer4" },
                new CustomerCollection() { Id = 483, Name = "Customer6" },
                new CustomerCollection() { Id = 484, Name = "Customer5" },
                new CustomerCollection() { Id = 485, Name = "Customer305" },
                new CustomerCollection() { Id = 486, Name = "Customer58" },
                new CustomerCollection() { Id = 487, Name = "Customer307" },
                new CustomerCollection() { Id = 488, Name = "Customer47" },
                new CustomerCollection() { Id = 489, Name = "Customer157" },
                new CustomerCollection() { Id = 490, Name = "Customer249" },
                new CustomerCollection() { Id = 491, Name = "Customer250" },
                new CustomerCollection() { Id = 492, Name = "Customer269" },
                new CustomerCollection() { Id = 493, Name = "Customer306" },
                new CustomerCollection() { Id = 494, Name = "Customer160" },
                new CustomerCollection() { Id = 495, Name = "Customer170" },
                new CustomerCollection() { Id = 496, Name = "Customer277" },
                new CustomerCollection() { Id = 497, Name = "Customer34" },
                new CustomerCollection() { Id = 498, Name = "Customer7" },
                new CustomerCollection() { Id = 499, Name = "Customer279" },
                new CustomerCollection() { Id = 500, Name = "Customer175" },
                new CustomerCollection() { Id = 501, Name = "Customer234" },
                new CustomerCollection() { Id = 503, Name = "Customer221" },
                new CustomerCollection() { Id = 504, Name = "Customer224" },
                new CustomerCollection() { Id = 505, Name = "Customer185" },
                new CustomerCollection() { Id = 506, Name = "Customer255" },
                new CustomerCollection() { Id = 507, Name = "Customer30" },
            };

            return await Task.FromResult(customers).ConfigureAwait(false);
        }
        public async Task<IList<ActivityCollection>> GetActivities()
        {
            var activities = new List<ActivityCollection>
            {
                new ActivityCollection() { Id = 55, Name = "Generic - Customer Support (Incident)" },
                new ActivityCollection() { Id = 53, Name = "Generic - Customer Support (Request)" },
                new ActivityCollection() { Id = 52, Name = "Generic - Customer Updates" },
                new ActivityCollection() { Id = 50, Name = "Implementation - DEV - Customization - Activity1" },
                new ActivityCollection() { Id = 51, Name = "Implementation - DEV - Customization - Activity2" },
                new ActivityCollection() { Id = 49, Name = "Implementation - DEV - Customization - Activity3" },
                new ActivityCollection() { Id = 48, Name = "Implementation - DEV - Customization - Activity4" },
                new ActivityCollection() { Id = 45, Name = "Implementation - IMPL - Configuration - Activity1" },
                new ActivityCollection() { Id = 42, Name = "Implementation - IMPL - Configuration - Activity2" },
                new ActivityCollection() { Id = 43, Name = "Implementation - IMPL - Configuration - Activity3" },
                new ActivityCollection() { Id = 38, Name = "Implementation - IMPL - Configuration - Activity4" },
                new ActivityCollection() { Id = 40, Name = "Implementation - IMPL - Configuration - Activity5" },
                new ActivityCollection() { Id = 44, Name = "Implementation - IMPL - Configuration - Activity6" },
                new ActivityCollection() { Id = 47, Name = "Implementation - IMPL - Configuration - Activity7" },
                new ActivityCollection() { Id = 46, Name = "Implementation - IMPL - Configuration - Activity8" },
                new ActivityCollection() { Id = 37, Name = "Implementation - IMPL - Configuration - Activity9" },
                new ActivityCollection() { Id = 39, Name = "Implementation - IMPL - Configuration - Activity10" },
                new ActivityCollection() { Id = 41, Name = "Implementation - IMPL - Configuration - Activity11" },
                new ActivityCollection() { Id = 3, Name = "Implementation - IMPL - Activity12" },
                new ActivityCollection() { Id = 36, Name = "Implementation - IMPL - Installation - System1" },
                new ActivityCollection() { Id = 34, Name = "Implementation - IMPL - Installation - System2" },
                new ActivityCollection() { Id = 35, Name = "Implementation - IMPL - Installation - System3" },
                new ActivityCollection() { Id = 1, Name = "Implementation - IMPL - Installation - System4" },
                new ActivityCollection() { Id = 16, Name = "Implementation - Implementation Planning Study" },
                new ActivityCollection() { Id = 2, Name = "Implementation - Spec - Training" },
                new ActivityCollection() { Id = 15, Name = "Implementation - Project management" },
                new ActivityCollection() { Id = 8, Name = "Internal Administrative Work" },
                new ActivityCollection() { Id = 7, Name = "Internal Meeting" },
                new ActivityCollection() { Id = 18, Name = "Operations - Release" },
                new ActivityCollection() { Id = 17, Name = "Operations - Troubleshooting" },
                new ActivityCollection() { Id = 22, Name = "POs/BAs - Acceptance testing" },
                new ActivityCollection() { Id = 21, Name = "POs/BAs - Analysis/Requirements" },
                new ActivityCollection() { Id = 23, Name = "POs/BAs - Demo" },
                new ActivityCollection() { Id = 24, Name = "POs/BAs - Meeting" },
                new ActivityCollection() { Id = 25, Name = "POs/BAs - Emails communication" },
                new ActivityCollection() { Id = 13, Name = "Sales Support" },
                new ActivityCollection() { Id = 4, Name = "Software Development - Bug Fixing" },
                new ActivityCollection() { Id = 9, Name = "Software Development - Design" },
                new ActivityCollection() { Id = 6, Name = "Software Development - Feature Implementation" },
                new ActivityCollection() { Id = 28, Name = "Software Development - Peer Review" },
                new ActivityCollection() { Id = 11, Name = "Software Development - Testing" },
                new ActivityCollection() { Id = 27, Name = "Software Development - Unplanned" },
                new ActivityCollection() { Id = 26, Name = "Technical Issues" },
            };
            return await Task.FromResult(activities.ToList()).ConfigureAwait(false);
        }
#pragma warning disable MA0051 // Method is too long
        public async Task<IList<TimesheetCollection>> GetTimesheets()
#pragma warning restore MA0051 // Method is too long
        {
            var timesheets = new List<TimesheetCollection>
            {
                new TimesheetCollection()
                {
                    Id = 1,
                    Activity = 1,
                    Project = 1,
                    Begin = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day - 1, 8, 0, 0),
                    End = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day -1, 9, 0, 0),
                    Duration = 3600,
                    Description = "Test Timesheet 1",
                    User = 1,
                },
                new TimesheetCollection()
                {
                    Id = 2,
                    Activity = 2,
                    Project = 2,
                    Begin = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day - 1, 9, 0, 0),
                    End = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day - 1, 10, 0, 0),
                    Duration = 3600,
                    Description = "Test Timesheet 2",
                    User = 1,
                },
                new TimesheetCollection()
                {
                    Id = 3,
                    Activity = 1,
                    Project = 1,
                    Begin = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day - 1, 10, 0, 0),
                    End = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day - 1, 11, 0, 0),
                    Duration = 3600,
                    Description = "Test Timesheet 3",
                    User = 1,
                },
                new TimesheetCollection()
                {
                    Id = 4,
                    Activity = 2,
                    Project = 2,
                    Begin = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 8, 0, 0),
                    End = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 9, 0, 0),
                    Duration = 3600,
                    Description = "Test Timesheet 4",
                    User = 1,
                },
                new TimesheetCollection()
                {
                    Id = 5,
                    Activity = 1,
                    Project = 1,
                    Begin = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 9, 0, 0),
                    End = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 10, 0, 0),
                    Duration = 3600,
                    Description = "Test Timesheet 5",
                    User = 1,
                },
                new TimesheetCollection()
                {
                    Id = 6,
                    Activity = 2,
                    Project = 2,
                    Begin = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 10, 0, 0),
                    End = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 11, 0, 0),
                    Duration = 3600,
                    Description = "Test Timesheet 6",
                    User = 1,
                },
            };

            return await Task.FromResult(timesheets).ConfigureAwait(false);
        }

        public Task<HttpOperationResponse> GetPing()
        {
            var ping = new HttpOperationResponse();

            return Task.FromResult(ping);
        }

        public Task<KimaiDotNet.Models.Version> GetVersion()
        {
            var version = new KimaiDotNet.Models.Version() { VersionProperty = "0.0.0.1" };
            return Task.FromResult(version);
        }

        public Task<TimesheetEntity> PostTimesheet(TimesheetEditForm timesheetEditForm)
        {
#pragma warning disable SCS0005 // Weak random number generator.
            int newId = rnd.Next(10, 10000);
#pragma warning restore SCS0005 // Weak random number generator.
            var timesheet = new TimesheetEntity()
            {
                Id = newId,
                Activity = timesheetEditForm.Activity,
                Project = timesheetEditForm.Project,
                User = timesheetEditForm.User,
                Begin = timesheetEditForm.Begin,
                End = timesheetEditForm.End,
                Description = timesheetEditForm.Description,
            };

            return Task.FromResult(timesheet);
        }

        public Task<UserEntity> GetCurrentUser()
        {
            var user = new UserEntity()
            {
                Id = 5,
            };

            return Task.FromResult(user);
        }
    }
}
