// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MarkZither.KimaiDotNet.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProjectEditForm
    {
        /// <summary>
        /// Initializes a new instance of the ProjectEditForm class.
        /// </summary>
        public ProjectEditForm()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectEditForm class.
        /// </summary>
        /// <param name="customer">Customer ID</param>
        /// <param name="color">The hexadecimal color code (default:
        /// #d2d6de)</param>
        public ProjectEditForm(string name, int customer, string comment = default(string), string orderNumber = default(string), System.DateTime? orderDate = default(System.DateTime?), System.DateTime? start = default(System.DateTime?), System.DateTime? end = default(System.DateTime?), string color = default(string), bool? visible = default(bool?))
        {
            Name = name;
            Comment = comment;
            OrderNumber = orderNumber;
            OrderDate = orderDate;
            Start = start;
            End = end;
            Customer = customer;
            Color = color;
            Visible = visible;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public string Comment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderDate")]
        public System.DateTime? OrderDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public System.DateTime? Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "end")]
        public System.DateTime? End { get; set; }

        /// <summary>
        /// Gets or sets customer ID
        /// </summary>
        [JsonProperty(PropertyName = "customer")]
        public int Customer { get; set; }

        /// <summary>
        /// Gets or sets the hexadecimal color code (default: #d2d6de)
        /// </summary>
        [JsonProperty(PropertyName = "color")]
        public string Color { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "visible")]
        public bool? Visible { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
