// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MarkZither.KimaiDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TimesheetEditForm
    {
        /// <summary>
        /// Initializes a new instance of the TimesheetEditForm class.
        /// </summary>
        public TimesheetEditForm()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TimesheetEditForm class.
        /// </summary>
        /// <param name="project">Project ID</param>
        /// <param name="activity">Activity ID</param>
        /// <param name="tags">Comma separated list of tags</param>
        /// <param name="fixedRate">Fixed rate</param>
        /// <param name="hourlyRate">Hourly rate</param>
        /// <param name="user">User ID</param>
        public TimesheetEditForm(System.DateTime begin, int project, int activity, System.DateTime? end = default(System.DateTime?), string duration = default(string), string description = default(string), string tags = default(string), double? fixedRate = default(double?), double? hourlyRate = default(double?), int? user = default(int?), bool? exported = default(bool?))
        {
            Begin = begin;
            End = end;
            Duration = duration;
            Project = project;
            Activity = activity;
            Description = description;
            Tags = tags;
            FixedRate = fixedRate;
            HourlyRate = hourlyRate;
            User = user;
            Exported = exported;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "begin")]
        public System.DateTime Begin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "end")]
        public System.DateTime? End { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public string Duration { get; set; }

        /// <summary>
        /// Gets or sets project ID
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public int Project { get; set; }

        /// <summary>
        /// Gets or sets activity ID
        /// </summary>
        [JsonProperty(PropertyName = "activity")]
        public int Activity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets comma separated list of tags
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public string Tags { get; set; }

        /// <summary>
        /// Gets or sets fixed rate
        /// </summary>
        [JsonProperty(PropertyName = "fixedRate")]
        public double? FixedRate { get; set; }

        /// <summary>
        /// Gets or sets hourly rate
        /// </summary>
        [JsonProperty(PropertyName = "hourlyRate")]
        public double? HourlyRate { get; set; }

        /// <summary>
        /// Gets or sets user ID
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public int? User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exported")]
        public bool? Exported { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
