// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MarkZither.KimaiDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TimesheetConfig
    {
        /// <summary>
        /// Initializes a new instance of the TimesheetConfig class.
        /// </summary>
        public TimesheetConfig()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TimesheetConfig class.
        /// </summary>
        /// <param name="trackingMode">The time-tracking mode, see also:
        /// https://www.kimai.org/documentation/timesheet.html#tracking-modes</param>
        /// <param name="defaultBeginTime">Default begin datetime in PHP
        /// format</param>
        /// <param name="activeEntriesHardLimit">How many running timesheets a
        /// user is allowed to have at the same time</param>
        /// <param name="activeEntriesSoftLimit">How many running timesheets a
        /// user is allowed before a warning is shown</param>
        /// <param name="isAllowFutureTimes">Whether entries for future times
        /// are allowed</param>
        /// <param name="isAllowOverlapping">Whether overlapping entries are
        /// allowed</param>
        public TimesheetConfig(string trackingMode = default(string), string defaultBeginTime = default(string), int? activeEntriesHardLimit = default(int?), int? activeEntriesSoftLimit = default(int?), bool? isAllowFutureTimes = default(bool?), bool? isAllowOverlapping = default(bool?))
        {
            TrackingMode = trackingMode;
            DefaultBeginTime = defaultBeginTime;
            ActiveEntriesHardLimit = activeEntriesHardLimit;
            ActiveEntriesSoftLimit = activeEntriesSoftLimit;
            IsAllowFutureTimes = isAllowFutureTimes;
            IsAllowOverlapping = isAllowOverlapping;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the time-tracking mode, see also:
        /// https://www.kimai.org/documentation/timesheet.html#tracking-modes
        /// </summary>
        [JsonProperty(PropertyName = "trackingMode")]
        public string TrackingMode { get; set; }

        /// <summary>
        /// Gets or sets default begin datetime in PHP format
        /// </summary>
        [JsonProperty(PropertyName = "defaultBeginTime")]
        public string DefaultBeginTime { get; set; }

        /// <summary>
        /// Gets or sets how many running timesheets a user is allowed to have
        /// at the same time
        /// </summary>
        [JsonProperty(PropertyName = "activeEntriesHardLimit")]
        public int? ActiveEntriesHardLimit { get; set; }

        /// <summary>
        /// Gets or sets how many running timesheets a user is allowed before a
        /// warning is shown
        /// </summary>
        [JsonProperty(PropertyName = "activeEntriesSoftLimit")]
        public int? ActiveEntriesSoftLimit { get; set; }

        /// <summary>
        /// Gets or sets whether entries for future times are allowed
        /// </summary>
        [JsonProperty(PropertyName = "isAllowFutureTimes")]
        public bool? IsAllowFutureTimes { get; set; }

        /// <summary>
        /// Gets or sets whether overlapping entries are allowed
        /// </summary>
        [JsonProperty(PropertyName = "isAllowOverlapping")]
        public bool? IsAllowOverlapping { get; set; }

    }
}
