// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MarkZither.KimaiDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Version
    {
        /// <summary>
        /// Initializes a new instance of the Version class.
        /// </summary>
        public Version()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Version class.
        /// </summary>
        /// <param name="versionProperty">Kimai Version, eg. "1.9"</param>
        /// <param name="candidate">Candidate: either "prod" or "dev"</param>
        /// <param name="semver">Full version including status, eg:
        /// "1.9-prod"</param>
        /// <param name="name">The version name</param>
        /// <param name="copyright">A full copyright notice</param>
        public Version(string versionProperty = default(string), string candidate = default(string), string semver = default(string), string name = default(string), string copyright = default(string))
        {
            VersionProperty = versionProperty;
            Candidate = candidate;
            Semver = semver;
            Name = name;
            Copyright = copyright;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets kimai Version, eg. "1.9"
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string VersionProperty { get; set; }

        /// <summary>
        /// Gets or sets candidate: either "prod" or "dev"
        /// </summary>
        [JsonProperty(PropertyName = "candidate")]
        public string Candidate { get; set; }

        /// <summary>
        /// Gets or sets full version including status, eg: "1.9-prod"
        /// </summary>
        [JsonProperty(PropertyName = "semver")]
        public string Semver { get; set; }

        /// <summary>
        /// Gets or sets the version name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a full copyright notice
        /// </summary>
        [JsonProperty(PropertyName = "copyright")]
        public string Copyright { get; set; }

    }
}
